name: Deploy AWS Account Post Merge Actions

on:
  pull_request:
    branches:
      - main  
    types: [closed] 

permissions:
  contents: read 
  id-token: write

jobs:
  ##################################################################################
  # 1. Zip the configuration and Upload to S3                                      
  ##################################################################################
  post_merge_actions:
    name: Perform Zip and Upload Actions
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'feature/add-account-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (merged base branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Zip Repository Contents
        id: zip_repo
        run: |
          ZIP_FILENAME="aws-accelerator-config.zip"
          echo "Zipping repository contents to $ZIP_FILENAME..."
          zip -r ${{ github.workspace }}/$ZIP_FILENAME . -x ".git/*" -x ".github/*"
          echo "Repository content zipped to ${{ github.workspace }}/$ZIP_FILENAME"
          ls -lh ${{ github.workspace }}/$ZIP_FILENAME
          echo "zip_filename=$ZIP_FILENAME" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload Package to S3
        env:

          S3_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET_NAME }}
          ZIP_FILE_PATH: "${{ github.workspace }}/${{ steps.zip_repo.outputs.zip_filename }}"
        run: |
          set -ex # Exit on error, print commands"

          S3_OBJECT_KEY="zipped/${{ steps.zip_repo.outputs.zip_filename }}"
     
          echo "Uploading $ZIP_FILE_PATH to s3://$S3_BUCKET/$S3_OBJECT_KEY ..."
          aws s3 cp "$ZIP_FILE_PATH" "s3://$S3_BUCKET/$S3_OBJECT_KEY"
          echo "Successfully uploaded $ZIP_FILE_PATH to s3://$S3_BUCKET/$S3_OBJECT_KEY"


###################################################################################
# Run apply workflow to trigger AWS CodePipeline.
# Wait for account creation.
# Send Slack notification with success/failure.
###################################################################################